# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f75303779d0bb21d775b8e5ab0b6296db5d823e42ea7becb272e6d7377e3dd11472c038996e61025c6682554d058a157b6cbe352539c12bdaa703da8bb3fc2f2

test:
  secret_key_base: cb6f9e113765d10c22d2986b024b0213a8f08302b5475ed2d12be3f77107447ff15987ae2458318453bd79e88e153430cd7fdaf77c82dd893024d3287b1404db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
